version: "3.8"

services:
  postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}_${RAILS_ENV}
    ports:
      - "5432:5432"
    volumes:
      - hsb-postgres:/var/lib/postgresql/data
  hsb:
    env_file: .env
    build: .
    volumes:
      - .:/opt/app
    depends_on:
      - postgres
    ports:
      - "8010:8010"
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    depends_on:
      - hsb
    ports:
      - "8020:8020"
volumes:
  hsb-postgres:
